version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Backend/ImpeccableService.Backend.API/ImpeccableService.Backend.API.csproj
      - dotnet tool install --global dotnet-ef
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output Backend/ImpeccableService.Backend.API/ImpeccableService.Backend.API.csproj
      - export ASPNETCORE_ENVIRONMENT=Production
      - export ProjectId=$PROJECT_ID
      - echo $ProjectId
      - #dotnet ef database update --project Backend/ImpeccableService.Backend.API
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
    - appspec.yml
